/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthRhColaboradoresIndexRouteImport } from './routes/_auth/rh/colaboradores/index'
import { Route as AuthGestaoRegiaoIndexRouteImport } from './routes/_auth/gestao/regiao/index'
import { Route as AuthGestaoGruposIndexRouteImport } from './routes/_auth/gestao/grupos/index'
import { Route as AuthGestaoEntregadoresIndexRouteImport } from './routes/_auth/gestao/entregadores/index'
import { Route as AuthGestaoClientesIndexRouteImport } from './routes/_auth/gestao/clientes/index'
import { Route as AuthRhColaboradoresNovoRouteImport } from './routes/_auth/rh/colaboradores/novo'
import { Route as AuthGestaoRegiaoRegionIdRouteImport } from './routes/_auth/gestao/regiao/$regionId'
import { Route as AuthGestaoGruposGroupIdRouteImport } from './routes/_auth/gestao/grupos/$groupId'
import { Route as AuthGestaoEntregadoresDeliverymanIdRouteImport } from './routes/_auth/gestao/entregadores/$deliverymanId'
import { Route as AuthGestaoClientesClientIdRouteImport } from './routes/_auth/gestao/clientes/$clientId'
import { Route as AuthRhColaboradoresUserIdEditarRouteImport } from './routes/_auth/rh/colaboradores/$userId.editar'
import { Route as AuthRhColaboradoresUserIdDetalheRouteImport } from './routes/_auth/rh/colaboradores/$userId.detalhe'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRhColaboradoresIndexRoute =
  AuthRhColaboradoresIndexRouteImport.update({
    id: '/rh/colaboradores/',
    path: '/rh/colaboradores/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoRegiaoIndexRoute = AuthGestaoRegiaoIndexRouteImport.update({
  id: '/gestao/regiao/',
  path: '/gestao/regiao/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoGruposIndexRoute = AuthGestaoGruposIndexRouteImport.update({
  id: '/gestao/grupos/',
  path: '/gestao/grupos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoEntregadoresIndexRoute =
  AuthGestaoEntregadoresIndexRouteImport.update({
    id: '/gestao/entregadores/',
    path: '/gestao/entregadores/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoClientesIndexRoute = AuthGestaoClientesIndexRouteImport.update({
  id: '/gestao/clientes/',
  path: '/gestao/clientes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRhColaboradoresNovoRoute = AuthRhColaboradoresNovoRouteImport.update({
  id: '/rh/colaboradores/novo',
  path: '/rh/colaboradores/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoRegiaoRegionIdRoute =
  AuthGestaoRegiaoRegionIdRouteImport.update({
    id: '/gestao/regiao/$regionId',
    path: '/gestao/regiao/$regionId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoGruposGroupIdRoute = AuthGestaoGruposGroupIdRouteImport.update({
  id: '/gestao/grupos/$groupId',
  path: '/gestao/grupos/$groupId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoEntregadoresDeliverymanIdRoute =
  AuthGestaoEntregadoresDeliverymanIdRouteImport.update({
    id: '/gestao/entregadores/$deliverymanId',
    path: '/gestao/entregadores/$deliverymanId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoClientesClientIdRoute =
  AuthGestaoClientesClientIdRouteImport.update({
    id: '/gestao/clientes/$clientId',
    path: '/gestao/clientes/$clientId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRhColaboradoresUserIdEditarRoute =
  AuthRhColaboradoresUserIdEditarRouteImport.update({
    id: '/rh/colaboradores/$userId/editar',
    path: '/rh/colaboradores/$userId/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRhColaboradoresUserIdDetalheRoute =
  AuthRhColaboradoresUserIdDetalheRouteImport.update({
    id: '/rh/colaboradores/$userId/detalhe',
    path: '/rh/colaboradores/$userId/detalhe',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/dashboard': typeof AuthDashboardRoute
  '/gestao/clientes/$clientId': typeof AuthGestaoClientesClientIdRoute
  '/gestao/entregadores/$deliverymanId': typeof AuthGestaoEntregadoresDeliverymanIdRoute
  '/gestao/grupos/$groupId': typeof AuthGestaoGruposGroupIdRoute
  '/gestao/regiao/$regionId': typeof AuthGestaoRegiaoRegionIdRoute
  '/rh/colaboradores/novo': typeof AuthRhColaboradoresNovoRoute
  '/gestao/clientes': typeof AuthGestaoClientesIndexRoute
  '/gestao/entregadores': typeof AuthGestaoEntregadoresIndexRoute
  '/gestao/grupos': typeof AuthGestaoGruposIndexRoute
  '/gestao/regiao': typeof AuthGestaoRegiaoIndexRoute
  '/rh/colaboradores': typeof AuthRhColaboradoresIndexRoute
  '/rh/colaboradores/$userId/detalhe': typeof AuthRhColaboradoresUserIdDetalheRoute
  '/rh/colaboradores/$userId/editar': typeof AuthRhColaboradoresUserIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/dashboard': typeof AuthDashboardRoute
  '/gestao/clientes/$clientId': typeof AuthGestaoClientesClientIdRoute
  '/gestao/entregadores/$deliverymanId': typeof AuthGestaoEntregadoresDeliverymanIdRoute
  '/gestao/grupos/$groupId': typeof AuthGestaoGruposGroupIdRoute
  '/gestao/regiao/$regionId': typeof AuthGestaoRegiaoRegionIdRoute
  '/rh/colaboradores/novo': typeof AuthRhColaboradoresNovoRoute
  '/gestao/clientes': typeof AuthGestaoClientesIndexRoute
  '/gestao/entregadores': typeof AuthGestaoEntregadoresIndexRoute
  '/gestao/grupos': typeof AuthGestaoGruposIndexRoute
  '/gestao/regiao': typeof AuthGestaoRegiaoIndexRoute
  '/rh/colaboradores': typeof AuthRhColaboradoresIndexRoute
  '/rh/colaboradores/$userId/detalhe': typeof AuthRhColaboradoresUserIdDetalheRoute
  '/rh/colaboradores/$userId/editar': typeof AuthRhColaboradoresUserIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/gestao/clientes/$clientId': typeof AuthGestaoClientesClientIdRoute
  '/_auth/gestao/entregadores/$deliverymanId': typeof AuthGestaoEntregadoresDeliverymanIdRoute
  '/_auth/gestao/grupos/$groupId': typeof AuthGestaoGruposGroupIdRoute
  '/_auth/gestao/regiao/$regionId': typeof AuthGestaoRegiaoRegionIdRoute
  '/_auth/rh/colaboradores/novo': typeof AuthRhColaboradoresNovoRoute
  '/_auth/gestao/clientes/': typeof AuthGestaoClientesIndexRoute
  '/_auth/gestao/entregadores/': typeof AuthGestaoEntregadoresIndexRoute
  '/_auth/gestao/grupos/': typeof AuthGestaoGruposIndexRoute
  '/_auth/gestao/regiao/': typeof AuthGestaoRegiaoIndexRoute
  '/_auth/rh/colaboradores/': typeof AuthRhColaboradoresIndexRoute
  '/_auth/rh/colaboradores/$userId/detalhe': typeof AuthRhColaboradoresUserIdDetalheRoute
  '/_auth/rh/colaboradores/$userId/editar': typeof AuthRhColaboradoresUserIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/trocar-senha'
    | '/dashboard'
    | '/gestao/clientes/$clientId'
    | '/gestao/entregadores/$deliverymanId'
    | '/gestao/grupos/$groupId'
    | '/gestao/regiao/$regionId'
    | '/rh/colaboradores/novo'
    | '/gestao/clientes'
    | '/gestao/entregadores'
    | '/gestao/grupos'
    | '/gestao/regiao'
    | '/rh/colaboradores'
    | '/rh/colaboradores/$userId/detalhe'
    | '/rh/colaboradores/$userId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/trocar-senha'
    | '/dashboard'
    | '/gestao/clientes/$clientId'
    | '/gestao/entregadores/$deliverymanId'
    | '/gestao/grupos/$groupId'
    | '/gestao/regiao/$regionId'
    | '/rh/colaboradores/novo'
    | '/gestao/clientes'
    | '/gestao/entregadores'
    | '/gestao/grupos'
    | '/gestao/regiao'
    | '/rh/colaboradores'
    | '/rh/colaboradores/$userId/detalhe'
    | '/rh/colaboradores/$userId/editar'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/trocar-senha'
    | '/_auth/dashboard'
    | '/_auth/gestao/clientes/$clientId'
    | '/_auth/gestao/entregadores/$deliverymanId'
    | '/_auth/gestao/grupos/$groupId'
    | '/_auth/gestao/regiao/$regionId'
    | '/_auth/rh/colaboradores/novo'
    | '/_auth/gestao/clientes/'
    | '/_auth/gestao/entregadores/'
    | '/_auth/gestao/grupos/'
    | '/_auth/gestao/regiao/'
    | '/_auth/rh/colaboradores/'
    | '/_auth/rh/colaboradores/$userId/detalhe'
    | '/_auth/rh/colaboradores/$userId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rh/colaboradores/': {
      id: '/_auth/rh/colaboradores/'
      path: '/rh/colaboradores'
      fullPath: '/rh/colaboradores'
      preLoaderRoute: typeof AuthRhColaboradoresIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/regiao/': {
      id: '/_auth/gestao/regiao/'
      path: '/gestao/regiao'
      fullPath: '/gestao/regiao'
      preLoaderRoute: typeof AuthGestaoRegiaoIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/grupos/': {
      id: '/_auth/gestao/grupos/'
      path: '/gestao/grupos'
      fullPath: '/gestao/grupos'
      preLoaderRoute: typeof AuthGestaoGruposIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/entregadores/': {
      id: '/_auth/gestao/entregadores/'
      path: '/gestao/entregadores'
      fullPath: '/gestao/entregadores'
      preLoaderRoute: typeof AuthGestaoEntregadoresIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/clientes/': {
      id: '/_auth/gestao/clientes/'
      path: '/gestao/clientes'
      fullPath: '/gestao/clientes'
      preLoaderRoute: typeof AuthGestaoClientesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rh/colaboradores/novo': {
      id: '/_auth/rh/colaboradores/novo'
      path: '/rh/colaboradores/novo'
      fullPath: '/rh/colaboradores/novo'
      preLoaderRoute: typeof AuthRhColaboradoresNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/regiao/$regionId': {
      id: '/_auth/gestao/regiao/$regionId'
      path: '/gestao/regiao/$regionId'
      fullPath: '/gestao/regiao/$regionId'
      preLoaderRoute: typeof AuthGestaoRegiaoRegionIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/grupos/$groupId': {
      id: '/_auth/gestao/grupos/$groupId'
      path: '/gestao/grupos/$groupId'
      fullPath: '/gestao/grupos/$groupId'
      preLoaderRoute: typeof AuthGestaoGruposGroupIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/entregadores/$deliverymanId': {
      id: '/_auth/gestao/entregadores/$deliverymanId'
      path: '/gestao/entregadores/$deliverymanId'
      fullPath: '/gestao/entregadores/$deliverymanId'
      preLoaderRoute: typeof AuthGestaoEntregadoresDeliverymanIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/clientes/$clientId': {
      id: '/_auth/gestao/clientes/$clientId'
      path: '/gestao/clientes/$clientId'
      fullPath: '/gestao/clientes/$clientId'
      preLoaderRoute: typeof AuthGestaoClientesClientIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rh/colaboradores/$userId/editar': {
      id: '/_auth/rh/colaboradores/$userId/editar'
      path: '/rh/colaboradores/$userId/editar'
      fullPath: '/rh/colaboradores/$userId/editar'
      preLoaderRoute: typeof AuthRhColaboradoresUserIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rh/colaboradores/$userId/detalhe': {
      id: '/_auth/rh/colaboradores/$userId/detalhe'
      path: '/rh/colaboradores/$userId/detalhe'
      fullPath: '/rh/colaboradores/$userId/detalhe'
      preLoaderRoute: typeof AuthRhColaboradoresUserIdDetalheRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthGestaoClientesClientIdRoute: typeof AuthGestaoClientesClientIdRoute
  AuthGestaoEntregadoresDeliverymanIdRoute: typeof AuthGestaoEntregadoresDeliverymanIdRoute
  AuthGestaoGruposGroupIdRoute: typeof AuthGestaoGruposGroupIdRoute
  AuthGestaoRegiaoRegionIdRoute: typeof AuthGestaoRegiaoRegionIdRoute
  AuthRhColaboradoresNovoRoute: typeof AuthRhColaboradoresNovoRoute
  AuthGestaoClientesIndexRoute: typeof AuthGestaoClientesIndexRoute
  AuthGestaoEntregadoresIndexRoute: typeof AuthGestaoEntregadoresIndexRoute
  AuthGestaoGruposIndexRoute: typeof AuthGestaoGruposIndexRoute
  AuthGestaoRegiaoIndexRoute: typeof AuthGestaoRegiaoIndexRoute
  AuthRhColaboradoresIndexRoute: typeof AuthRhColaboradoresIndexRoute
  AuthRhColaboradoresUserIdDetalheRoute: typeof AuthRhColaboradoresUserIdDetalheRoute
  AuthRhColaboradoresUserIdEditarRoute: typeof AuthRhColaboradoresUserIdEditarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthGestaoClientesClientIdRoute: AuthGestaoClientesClientIdRoute,
  AuthGestaoEntregadoresDeliverymanIdRoute:
    AuthGestaoEntregadoresDeliverymanIdRoute,
  AuthGestaoGruposGroupIdRoute: AuthGestaoGruposGroupIdRoute,
  AuthGestaoRegiaoRegionIdRoute: AuthGestaoRegiaoRegionIdRoute,
  AuthRhColaboradoresNovoRoute: AuthRhColaboradoresNovoRoute,
  AuthGestaoClientesIndexRoute: AuthGestaoClientesIndexRoute,
  AuthGestaoEntregadoresIndexRoute: AuthGestaoEntregadoresIndexRoute,
  AuthGestaoGruposIndexRoute: AuthGestaoGruposIndexRoute,
  AuthGestaoRegiaoIndexRoute: AuthGestaoRegiaoIndexRoute,
  AuthRhColaboradoresIndexRoute: AuthRhColaboradoresIndexRoute,
  AuthRhColaboradoresUserIdDetalheRoute: AuthRhColaboradoresUserIdDetalheRoute,
  AuthRhColaboradoresUserIdEditarRoute: AuthRhColaboradoresUserIdEditarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
