/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthRhColaboradoresIndexRouteImport } from './routes/_auth/rh/colaboradores/index'
import { Route as AuthOperacionalPlanejamentoIndexRouteImport } from './routes/_auth/operacional/planejamento/index'
import { Route as AuthGestaoRegiaoIndexRouteImport } from './routes/_auth/gestao/regiao/index'
import { Route as AuthGestaoGruposIndexRouteImport } from './routes/_auth/gestao/grupos/index'
import { Route as AuthGestaoEntregadoresIndexRouteImport } from './routes/_auth/gestao/entregadores/index'
import { Route as AuthGestaoClientesIndexRouteImport } from './routes/_auth/gestao/clientes/index'
import { Route as AuthRhColaboradoresNovoRouteImport } from './routes/_auth/rh/colaboradores/novo'
import { Route as AuthGestaoRegiaoNovoRouteImport } from './routes/_auth/gestao/regiao/novo'
import { Route as AuthGestaoGruposNovoRouteImport } from './routes/_auth/gestao/grupos/novo'
import { Route as AuthGestaoEntregadoresNovoRouteImport } from './routes/_auth/gestao/entregadores/novo'
import { Route as AuthGestaoClientesNovoRouteImport } from './routes/_auth/gestao/clientes/novo'
import { Route as AuthRhColaboradoresUserIdEditarRouteImport } from './routes/_auth/rh/colaboradores/$userId.editar'
import { Route as AuthRhColaboradoresUserIdDetalheRouteImport } from './routes/_auth/rh/colaboradores/$userId.detalhe'
import { Route as AuthGestaoRegiaoRegionIdEditarRouteImport } from './routes/_auth/gestao/regiao/$regionId.editar'
import { Route as AuthGestaoRegiaoRegionIdDetalheRouteImport } from './routes/_auth/gestao/regiao/$regionId.detalhe'
import { Route as AuthGestaoGruposGroupIdEditarRouteImport } from './routes/_auth/gestao/grupos/$groupId.editar'
import { Route as AuthGestaoGruposGroupIdDetalheRouteImport } from './routes/_auth/gestao/grupos/$groupId.detalhe'
import { Route as AuthGestaoEntregadoresDeliverymanIdEditarRouteImport } from './routes/_auth/gestao/entregadores/$deliverymanId.editar'
import { Route as AuthGestaoEntregadoresDeliverymanIdDetalheRouteImport } from './routes/_auth/gestao/entregadores/$deliverymanId.detalhe'
import { Route as AuthGestaoClientesClientIdEditarRouteImport } from './routes/_auth/gestao/clientes/$clientId.editar'
import { Route as AuthGestaoClientesClientIdDetalheRouteImport } from './routes/_auth/gestao/clientes/$clientId.detalhe'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRhColaboradoresIndexRoute =
  AuthRhColaboradoresIndexRouteImport.update({
    id: '/rh/colaboradores/',
    path: '/rh/colaboradores/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOperacionalPlanejamentoIndexRoute =
  AuthOperacionalPlanejamentoIndexRouteImport.update({
    id: '/operacional/planejamento/',
    path: '/operacional/planejamento/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoRegiaoIndexRoute = AuthGestaoRegiaoIndexRouteImport.update({
  id: '/gestao/regiao/',
  path: '/gestao/regiao/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoGruposIndexRoute = AuthGestaoGruposIndexRouteImport.update({
  id: '/gestao/grupos/',
  path: '/gestao/grupos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoEntregadoresIndexRoute =
  AuthGestaoEntregadoresIndexRouteImport.update({
    id: '/gestao/entregadores/',
    path: '/gestao/entregadores/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoClientesIndexRoute = AuthGestaoClientesIndexRouteImport.update({
  id: '/gestao/clientes/',
  path: '/gestao/clientes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRhColaboradoresNovoRoute = AuthRhColaboradoresNovoRouteImport.update({
  id: '/rh/colaboradores/novo',
  path: '/rh/colaboradores/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoRegiaoNovoRoute = AuthGestaoRegiaoNovoRouteImport.update({
  id: '/gestao/regiao/novo',
  path: '/gestao/regiao/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoGruposNovoRoute = AuthGestaoGruposNovoRouteImport.update({
  id: '/gestao/grupos/novo',
  path: '/gestao/grupos/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestaoEntregadoresNovoRoute =
  AuthGestaoEntregadoresNovoRouteImport.update({
    id: '/gestao/entregadores/novo',
    path: '/gestao/entregadores/novo',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoClientesNovoRoute = AuthGestaoClientesNovoRouteImport.update({
  id: '/gestao/clientes/novo',
  path: '/gestao/clientes/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRhColaboradoresUserIdEditarRoute =
  AuthRhColaboradoresUserIdEditarRouteImport.update({
    id: '/rh/colaboradores/$userId/editar',
    path: '/rh/colaboradores/$userId/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRhColaboradoresUserIdDetalheRoute =
  AuthRhColaboradoresUserIdDetalheRouteImport.update({
    id: '/rh/colaboradores/$userId/detalhe',
    path: '/rh/colaboradores/$userId/detalhe',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoRegiaoRegionIdEditarRoute =
  AuthGestaoRegiaoRegionIdEditarRouteImport.update({
    id: '/gestao/regiao/$regionId/editar',
    path: '/gestao/regiao/$regionId/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoRegiaoRegionIdDetalheRoute =
  AuthGestaoRegiaoRegionIdDetalheRouteImport.update({
    id: '/gestao/regiao/$regionId/detalhe',
    path: '/gestao/regiao/$regionId/detalhe',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoGruposGroupIdEditarRoute =
  AuthGestaoGruposGroupIdEditarRouteImport.update({
    id: '/gestao/grupos/$groupId/editar',
    path: '/gestao/grupos/$groupId/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoGruposGroupIdDetalheRoute =
  AuthGestaoGruposGroupIdDetalheRouteImport.update({
    id: '/gestao/grupos/$groupId/detalhe',
    path: '/gestao/grupos/$groupId/detalhe',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoEntregadoresDeliverymanIdEditarRoute =
  AuthGestaoEntregadoresDeliverymanIdEditarRouteImport.update({
    id: '/gestao/entregadores/$deliverymanId/editar',
    path: '/gestao/entregadores/$deliverymanId/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoEntregadoresDeliverymanIdDetalheRoute =
  AuthGestaoEntregadoresDeliverymanIdDetalheRouteImport.update({
    id: '/gestao/entregadores/$deliverymanId/detalhe',
    path: '/gestao/entregadores/$deliverymanId/detalhe',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoClientesClientIdEditarRoute =
  AuthGestaoClientesClientIdEditarRouteImport.update({
    id: '/gestao/clientes/$clientId/editar',
    path: '/gestao/clientes/$clientId/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGestaoClientesClientIdDetalheRoute =
  AuthGestaoClientesClientIdDetalheRouteImport.update({
    id: '/gestao/clientes/$clientId/detalhe',
    path: '/gestao/clientes/$clientId/detalhe',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/dashboard': typeof AuthDashboardRoute
  '/gestao/clientes/novo': typeof AuthGestaoClientesNovoRoute
  '/gestao/entregadores/novo': typeof AuthGestaoEntregadoresNovoRoute
  '/gestao/grupos/novo': typeof AuthGestaoGruposNovoRoute
  '/gestao/regiao/novo': typeof AuthGestaoRegiaoNovoRoute
  '/rh/colaboradores/novo': typeof AuthRhColaboradoresNovoRoute
  '/gestao/clientes': typeof AuthGestaoClientesIndexRoute
  '/gestao/entregadores': typeof AuthGestaoEntregadoresIndexRoute
  '/gestao/grupos': typeof AuthGestaoGruposIndexRoute
  '/gestao/regiao': typeof AuthGestaoRegiaoIndexRoute
  '/operacional/planejamento': typeof AuthOperacionalPlanejamentoIndexRoute
  '/rh/colaboradores': typeof AuthRhColaboradoresIndexRoute
  '/gestao/clientes/$clientId/detalhe': typeof AuthGestaoClientesClientIdDetalheRoute
  '/gestao/clientes/$clientId/editar': typeof AuthGestaoClientesClientIdEditarRoute
  '/gestao/entregadores/$deliverymanId/detalhe': typeof AuthGestaoEntregadoresDeliverymanIdDetalheRoute
  '/gestao/entregadores/$deliverymanId/editar': typeof AuthGestaoEntregadoresDeliverymanIdEditarRoute
  '/gestao/grupos/$groupId/detalhe': typeof AuthGestaoGruposGroupIdDetalheRoute
  '/gestao/grupos/$groupId/editar': typeof AuthGestaoGruposGroupIdEditarRoute
  '/gestao/regiao/$regionId/detalhe': typeof AuthGestaoRegiaoRegionIdDetalheRoute
  '/gestao/regiao/$regionId/editar': typeof AuthGestaoRegiaoRegionIdEditarRoute
  '/rh/colaboradores/$userId/detalhe': typeof AuthRhColaboradoresUserIdDetalheRoute
  '/rh/colaboradores/$userId/editar': typeof AuthRhColaboradoresUserIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/dashboard': typeof AuthDashboardRoute
  '/gestao/clientes/novo': typeof AuthGestaoClientesNovoRoute
  '/gestao/entregadores/novo': typeof AuthGestaoEntregadoresNovoRoute
  '/gestao/grupos/novo': typeof AuthGestaoGruposNovoRoute
  '/gestao/regiao/novo': typeof AuthGestaoRegiaoNovoRoute
  '/rh/colaboradores/novo': typeof AuthRhColaboradoresNovoRoute
  '/gestao/clientes': typeof AuthGestaoClientesIndexRoute
  '/gestao/entregadores': typeof AuthGestaoEntregadoresIndexRoute
  '/gestao/grupos': typeof AuthGestaoGruposIndexRoute
  '/gestao/regiao': typeof AuthGestaoRegiaoIndexRoute
  '/operacional/planejamento': typeof AuthOperacionalPlanejamentoIndexRoute
  '/rh/colaboradores': typeof AuthRhColaboradoresIndexRoute
  '/gestao/clientes/$clientId/detalhe': typeof AuthGestaoClientesClientIdDetalheRoute
  '/gestao/clientes/$clientId/editar': typeof AuthGestaoClientesClientIdEditarRoute
  '/gestao/entregadores/$deliverymanId/detalhe': typeof AuthGestaoEntregadoresDeliverymanIdDetalheRoute
  '/gestao/entregadores/$deliverymanId/editar': typeof AuthGestaoEntregadoresDeliverymanIdEditarRoute
  '/gestao/grupos/$groupId/detalhe': typeof AuthGestaoGruposGroupIdDetalheRoute
  '/gestao/grupos/$groupId/editar': typeof AuthGestaoGruposGroupIdEditarRoute
  '/gestao/regiao/$regionId/detalhe': typeof AuthGestaoRegiaoRegionIdDetalheRoute
  '/gestao/regiao/$regionId/editar': typeof AuthGestaoRegiaoRegionIdEditarRoute
  '/rh/colaboradores/$userId/detalhe': typeof AuthRhColaboradoresUserIdDetalheRoute
  '/rh/colaboradores/$userId/editar': typeof AuthRhColaboradoresUserIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/gestao/clientes/novo': typeof AuthGestaoClientesNovoRoute
  '/_auth/gestao/entregadores/novo': typeof AuthGestaoEntregadoresNovoRoute
  '/_auth/gestao/grupos/novo': typeof AuthGestaoGruposNovoRoute
  '/_auth/gestao/regiao/novo': typeof AuthGestaoRegiaoNovoRoute
  '/_auth/rh/colaboradores/novo': typeof AuthRhColaboradoresNovoRoute
  '/_auth/gestao/clientes/': typeof AuthGestaoClientesIndexRoute
  '/_auth/gestao/entregadores/': typeof AuthGestaoEntregadoresIndexRoute
  '/_auth/gestao/grupos/': typeof AuthGestaoGruposIndexRoute
  '/_auth/gestao/regiao/': typeof AuthGestaoRegiaoIndexRoute
  '/_auth/operacional/planejamento/': typeof AuthOperacionalPlanejamentoIndexRoute
  '/_auth/rh/colaboradores/': typeof AuthRhColaboradoresIndexRoute
  '/_auth/gestao/clientes/$clientId/detalhe': typeof AuthGestaoClientesClientIdDetalheRoute
  '/_auth/gestao/clientes/$clientId/editar': typeof AuthGestaoClientesClientIdEditarRoute
  '/_auth/gestao/entregadores/$deliverymanId/detalhe': typeof AuthGestaoEntregadoresDeliverymanIdDetalheRoute
  '/_auth/gestao/entregadores/$deliverymanId/editar': typeof AuthGestaoEntregadoresDeliverymanIdEditarRoute
  '/_auth/gestao/grupos/$groupId/detalhe': typeof AuthGestaoGruposGroupIdDetalheRoute
  '/_auth/gestao/grupos/$groupId/editar': typeof AuthGestaoGruposGroupIdEditarRoute
  '/_auth/gestao/regiao/$regionId/detalhe': typeof AuthGestaoRegiaoRegionIdDetalheRoute
  '/_auth/gestao/regiao/$regionId/editar': typeof AuthGestaoRegiaoRegionIdEditarRoute
  '/_auth/rh/colaboradores/$userId/detalhe': typeof AuthRhColaboradoresUserIdDetalheRoute
  '/_auth/rh/colaboradores/$userId/editar': typeof AuthRhColaboradoresUserIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/trocar-senha'
    | '/dashboard'
    | '/gestao/clientes/novo'
    | '/gestao/entregadores/novo'
    | '/gestao/grupos/novo'
    | '/gestao/regiao/novo'
    | '/rh/colaboradores/novo'
    | '/gestao/clientes'
    | '/gestao/entregadores'
    | '/gestao/grupos'
    | '/gestao/regiao'
    | '/operacional/planejamento'
    | '/rh/colaboradores'
    | '/gestao/clientes/$clientId/detalhe'
    | '/gestao/clientes/$clientId/editar'
    | '/gestao/entregadores/$deliverymanId/detalhe'
    | '/gestao/entregadores/$deliverymanId/editar'
    | '/gestao/grupos/$groupId/detalhe'
    | '/gestao/grupos/$groupId/editar'
    | '/gestao/regiao/$regionId/detalhe'
    | '/gestao/regiao/$regionId/editar'
    | '/rh/colaboradores/$userId/detalhe'
    | '/rh/colaboradores/$userId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/trocar-senha'
    | '/dashboard'
    | '/gestao/clientes/novo'
    | '/gestao/entregadores/novo'
    | '/gestao/grupos/novo'
    | '/gestao/regiao/novo'
    | '/rh/colaboradores/novo'
    | '/gestao/clientes'
    | '/gestao/entregadores'
    | '/gestao/grupos'
    | '/gestao/regiao'
    | '/operacional/planejamento'
    | '/rh/colaboradores'
    | '/gestao/clientes/$clientId/detalhe'
    | '/gestao/clientes/$clientId/editar'
    | '/gestao/entregadores/$deliverymanId/detalhe'
    | '/gestao/entregadores/$deliverymanId/editar'
    | '/gestao/grupos/$groupId/detalhe'
    | '/gestao/grupos/$groupId/editar'
    | '/gestao/regiao/$regionId/detalhe'
    | '/gestao/regiao/$regionId/editar'
    | '/rh/colaboradores/$userId/detalhe'
    | '/rh/colaboradores/$userId/editar'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/trocar-senha'
    | '/_auth/dashboard'
    | '/_auth/gestao/clientes/novo'
    | '/_auth/gestao/entregadores/novo'
    | '/_auth/gestao/grupos/novo'
    | '/_auth/gestao/regiao/novo'
    | '/_auth/rh/colaboradores/novo'
    | '/_auth/gestao/clientes/'
    | '/_auth/gestao/entregadores/'
    | '/_auth/gestao/grupos/'
    | '/_auth/gestao/regiao/'
    | '/_auth/operacional/planejamento/'
    | '/_auth/rh/colaboradores/'
    | '/_auth/gestao/clientes/$clientId/detalhe'
    | '/_auth/gestao/clientes/$clientId/editar'
    | '/_auth/gestao/entregadores/$deliverymanId/detalhe'
    | '/_auth/gestao/entregadores/$deliverymanId/editar'
    | '/_auth/gestao/grupos/$groupId/detalhe'
    | '/_auth/gestao/grupos/$groupId/editar'
    | '/_auth/gestao/regiao/$regionId/detalhe'
    | '/_auth/gestao/regiao/$regionId/editar'
    | '/_auth/rh/colaboradores/$userId/detalhe'
    | '/_auth/rh/colaboradores/$userId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rh/colaboradores/': {
      id: '/_auth/rh/colaboradores/'
      path: '/rh/colaboradores'
      fullPath: '/rh/colaboradores'
      preLoaderRoute: typeof AuthRhColaboradoresIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/operacional/planejamento/': {
      id: '/_auth/operacional/planejamento/'
      path: '/operacional/planejamento'
      fullPath: '/operacional/planejamento'
      preLoaderRoute: typeof AuthOperacionalPlanejamentoIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/regiao/': {
      id: '/_auth/gestao/regiao/'
      path: '/gestao/regiao'
      fullPath: '/gestao/regiao'
      preLoaderRoute: typeof AuthGestaoRegiaoIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/grupos/': {
      id: '/_auth/gestao/grupos/'
      path: '/gestao/grupos'
      fullPath: '/gestao/grupos'
      preLoaderRoute: typeof AuthGestaoGruposIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/entregadores/': {
      id: '/_auth/gestao/entregadores/'
      path: '/gestao/entregadores'
      fullPath: '/gestao/entregadores'
      preLoaderRoute: typeof AuthGestaoEntregadoresIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/clientes/': {
      id: '/_auth/gestao/clientes/'
      path: '/gestao/clientes'
      fullPath: '/gestao/clientes'
      preLoaderRoute: typeof AuthGestaoClientesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rh/colaboradores/novo': {
      id: '/_auth/rh/colaboradores/novo'
      path: '/rh/colaboradores/novo'
      fullPath: '/rh/colaboradores/novo'
      preLoaderRoute: typeof AuthRhColaboradoresNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/regiao/novo': {
      id: '/_auth/gestao/regiao/novo'
      path: '/gestao/regiao/novo'
      fullPath: '/gestao/regiao/novo'
      preLoaderRoute: typeof AuthGestaoRegiaoNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/grupos/novo': {
      id: '/_auth/gestao/grupos/novo'
      path: '/gestao/grupos/novo'
      fullPath: '/gestao/grupos/novo'
      preLoaderRoute: typeof AuthGestaoGruposNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/entregadores/novo': {
      id: '/_auth/gestao/entregadores/novo'
      path: '/gestao/entregadores/novo'
      fullPath: '/gestao/entregadores/novo'
      preLoaderRoute: typeof AuthGestaoEntregadoresNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/clientes/novo': {
      id: '/_auth/gestao/clientes/novo'
      path: '/gestao/clientes/novo'
      fullPath: '/gestao/clientes/novo'
      preLoaderRoute: typeof AuthGestaoClientesNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rh/colaboradores/$userId/editar': {
      id: '/_auth/rh/colaboradores/$userId/editar'
      path: '/rh/colaboradores/$userId/editar'
      fullPath: '/rh/colaboradores/$userId/editar'
      preLoaderRoute: typeof AuthRhColaboradoresUserIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rh/colaboradores/$userId/detalhe': {
      id: '/_auth/rh/colaboradores/$userId/detalhe'
      path: '/rh/colaboradores/$userId/detalhe'
      fullPath: '/rh/colaboradores/$userId/detalhe'
      preLoaderRoute: typeof AuthRhColaboradoresUserIdDetalheRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/regiao/$regionId/editar': {
      id: '/_auth/gestao/regiao/$regionId/editar'
      path: '/gestao/regiao/$regionId/editar'
      fullPath: '/gestao/regiao/$regionId/editar'
      preLoaderRoute: typeof AuthGestaoRegiaoRegionIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/regiao/$regionId/detalhe': {
      id: '/_auth/gestao/regiao/$regionId/detalhe'
      path: '/gestao/regiao/$regionId/detalhe'
      fullPath: '/gestao/regiao/$regionId/detalhe'
      preLoaderRoute: typeof AuthGestaoRegiaoRegionIdDetalheRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/grupos/$groupId/editar': {
      id: '/_auth/gestao/grupos/$groupId/editar'
      path: '/gestao/grupos/$groupId/editar'
      fullPath: '/gestao/grupos/$groupId/editar'
      preLoaderRoute: typeof AuthGestaoGruposGroupIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/grupos/$groupId/detalhe': {
      id: '/_auth/gestao/grupos/$groupId/detalhe'
      path: '/gestao/grupos/$groupId/detalhe'
      fullPath: '/gestao/grupos/$groupId/detalhe'
      preLoaderRoute: typeof AuthGestaoGruposGroupIdDetalheRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/entregadores/$deliverymanId/editar': {
      id: '/_auth/gestao/entregadores/$deliverymanId/editar'
      path: '/gestao/entregadores/$deliverymanId/editar'
      fullPath: '/gestao/entregadores/$deliverymanId/editar'
      preLoaderRoute: typeof AuthGestaoEntregadoresDeliverymanIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/entregadores/$deliverymanId/detalhe': {
      id: '/_auth/gestao/entregadores/$deliverymanId/detalhe'
      path: '/gestao/entregadores/$deliverymanId/detalhe'
      fullPath: '/gestao/entregadores/$deliverymanId/detalhe'
      preLoaderRoute: typeof AuthGestaoEntregadoresDeliverymanIdDetalheRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/clientes/$clientId/editar': {
      id: '/_auth/gestao/clientes/$clientId/editar'
      path: '/gestao/clientes/$clientId/editar'
      fullPath: '/gestao/clientes/$clientId/editar'
      preLoaderRoute: typeof AuthGestaoClientesClientIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestao/clientes/$clientId/detalhe': {
      id: '/_auth/gestao/clientes/$clientId/detalhe'
      path: '/gestao/clientes/$clientId/detalhe'
      fullPath: '/gestao/clientes/$clientId/detalhe'
      preLoaderRoute: typeof AuthGestaoClientesClientIdDetalheRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthGestaoClientesNovoRoute: typeof AuthGestaoClientesNovoRoute
  AuthGestaoEntregadoresNovoRoute: typeof AuthGestaoEntregadoresNovoRoute
  AuthGestaoGruposNovoRoute: typeof AuthGestaoGruposNovoRoute
  AuthGestaoRegiaoNovoRoute: typeof AuthGestaoRegiaoNovoRoute
  AuthRhColaboradoresNovoRoute: typeof AuthRhColaboradoresNovoRoute
  AuthGestaoClientesIndexRoute: typeof AuthGestaoClientesIndexRoute
  AuthGestaoEntregadoresIndexRoute: typeof AuthGestaoEntregadoresIndexRoute
  AuthGestaoGruposIndexRoute: typeof AuthGestaoGruposIndexRoute
  AuthGestaoRegiaoIndexRoute: typeof AuthGestaoRegiaoIndexRoute
  AuthOperacionalPlanejamentoIndexRoute: typeof AuthOperacionalPlanejamentoIndexRoute
  AuthRhColaboradoresIndexRoute: typeof AuthRhColaboradoresIndexRoute
  AuthGestaoClientesClientIdDetalheRoute: typeof AuthGestaoClientesClientIdDetalheRoute
  AuthGestaoClientesClientIdEditarRoute: typeof AuthGestaoClientesClientIdEditarRoute
  AuthGestaoEntregadoresDeliverymanIdDetalheRoute: typeof AuthGestaoEntregadoresDeliverymanIdDetalheRoute
  AuthGestaoEntregadoresDeliverymanIdEditarRoute: typeof AuthGestaoEntregadoresDeliverymanIdEditarRoute
  AuthGestaoGruposGroupIdDetalheRoute: typeof AuthGestaoGruposGroupIdDetalheRoute
  AuthGestaoGruposGroupIdEditarRoute: typeof AuthGestaoGruposGroupIdEditarRoute
  AuthGestaoRegiaoRegionIdDetalheRoute: typeof AuthGestaoRegiaoRegionIdDetalheRoute
  AuthGestaoRegiaoRegionIdEditarRoute: typeof AuthGestaoRegiaoRegionIdEditarRoute
  AuthRhColaboradoresUserIdDetalheRoute: typeof AuthRhColaboradoresUserIdDetalheRoute
  AuthRhColaboradoresUserIdEditarRoute: typeof AuthRhColaboradoresUserIdEditarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthGestaoClientesNovoRoute: AuthGestaoClientesNovoRoute,
  AuthGestaoEntregadoresNovoRoute: AuthGestaoEntregadoresNovoRoute,
  AuthGestaoGruposNovoRoute: AuthGestaoGruposNovoRoute,
  AuthGestaoRegiaoNovoRoute: AuthGestaoRegiaoNovoRoute,
  AuthRhColaboradoresNovoRoute: AuthRhColaboradoresNovoRoute,
  AuthGestaoClientesIndexRoute: AuthGestaoClientesIndexRoute,
  AuthGestaoEntregadoresIndexRoute: AuthGestaoEntregadoresIndexRoute,
  AuthGestaoGruposIndexRoute: AuthGestaoGruposIndexRoute,
  AuthGestaoRegiaoIndexRoute: AuthGestaoRegiaoIndexRoute,
  AuthOperacionalPlanejamentoIndexRoute: AuthOperacionalPlanejamentoIndexRoute,
  AuthRhColaboradoresIndexRoute: AuthRhColaboradoresIndexRoute,
  AuthGestaoClientesClientIdDetalheRoute:
    AuthGestaoClientesClientIdDetalheRoute,
  AuthGestaoClientesClientIdEditarRoute: AuthGestaoClientesClientIdEditarRoute,
  AuthGestaoEntregadoresDeliverymanIdDetalheRoute:
    AuthGestaoEntregadoresDeliverymanIdDetalheRoute,
  AuthGestaoEntregadoresDeliverymanIdEditarRoute:
    AuthGestaoEntregadoresDeliverymanIdEditarRoute,
  AuthGestaoGruposGroupIdDetalheRoute: AuthGestaoGruposGroupIdDetalheRoute,
  AuthGestaoGruposGroupIdEditarRoute: AuthGestaoGruposGroupIdEditarRoute,
  AuthGestaoRegiaoRegionIdDetalheRoute: AuthGestaoRegiaoRegionIdDetalheRoute,
  AuthGestaoRegiaoRegionIdEditarRoute: AuthGestaoRegiaoRegionIdEditarRoute,
  AuthRhColaboradoresUserIdDetalheRoute: AuthRhColaboradoresUserIdDetalheRoute,
  AuthRhColaboradoresUserIdEditarRoute: AuthRhColaboradoresUserIdEditarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
